srv/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls , name='Programer'),
    path('', include('shop.urls')),
]

shop/models.py
from django.contrib.auth.models import Group, User
from django.db import models


# Create your models here

class Expert(models.Model):
    user        = models.OneToOneField(to=User,on_delete=models.CASCADE)
    username    = models.CharField(max_length=35)
    first_name  = models.CharField(max_length=35)
    last_name   = models.CharField(max_length=35)
    image       = models.ImageField(upload_to='image expert/', default='image/avatar.png', blank=True, null=True)
    address     = models.CharField(max_length=250)
    phone       = models.CharField(max_length=12)
    email       = models.EmailField(max_length=254)
    category    = models.ManyToManyField(to='Category')
    def __str__(self):
        return self.username

class Customer(models.Model):
    user        = models.OneToOneField(to=User , on_delete=models.CASCADE)
    username    = models.CharField(max_length=35)
    first_name  = models.CharField(max_length=35)
    last_name   = models.CharField(max_length=35)
    phone       = models.CharField(max_length=12)
    email       = models.EmailField(max_length=254)
    def __str__(self):
        return self.username
    
class Tag(models.Model):
    title = models.CharField(max_length=35)
    def __str__(self):
        return self.title
    
class Category(models.Model):
    title   = models.CharField(max_length=35)
    image   = models.ImageField(upload_to='image category/', default='image/default.jpg', blank=True, null=True)
    description = models.CharField(max_length=255 , blank=True , null=True)
    hashtag = models.CharField(max_length=200 , null=True)
    tag     = models.ForeignKey(to=Tag,on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
class Request_srv(models.Model):
    title       = models.CharField(max_length=35)
    phone       = models.CharField(max_length=12)
    address     = models.CharField(max_length=100)
    category    = models.ForeignKey(to=Category,on_delete=models.CASCADE)
    description = models.CharField(max_length=300,blank=True,null=True)
    expert      = models.ForeignKey(to=Expert,on_delete=models.CASCADE)
    customer    = models.ForeignKey(to=Customer,on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

media/templates/home/category.html
{% extends 'home/main.html' %}
{% load static %}
{% block body %}
<div class="album py-5">
    <div class="container">
      <div class="row row-cols-1 row-cols-md-2">
          {% for expert in experts %}
            <div class="card mb-4" style="max-width: 540px;">
                <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{expert.image.url}}" class="card-img" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                    <h5 class="card-title">{{expert.first_name}} {{expert.last_name}}</h5>
                    <p class="card-text"><small>{{expert.phone}}</small></p>
                    <p class="card-text"><small>{{expert.address}}</small></p>
                    {% if request.user.customer %}
                        <p class="card-text float-right"><a class="btn btn-info" href="{% url 'request_srv' expert.id %}">درخواست</a></p>
                    {% else %}
                        <p class="btn btn-info">شما برای ثبت درخواست باید حتما با حساب مشتری وارد شوید.</p>
                    {% endif %}
                    </div>
                </div>
                </div>
            </div>
          {% endfor %}
      </div>
    </div>
</div>
{% endblock body %}

media/templates/home/header.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Coding</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% for tag in tags %}
            <li class="nav-item dropdown active">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <small>{{tag.title}}</small>
              </a> 
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for category in tag.category_set.all %}
                    <a class="dropdown-item" href="{% url 'category' category.id %}">{{category.title}}</a>
                  {% endfor %}
              </div>
            </li>  
            {% endfor %}
          </ul>

          <ul class="navbar-nav nav-flex-icons">
            {% if request.user.is_authenticated %}
              {% if request.user.customer %}
                <li class="nav-item">
                  <a href="{% url 'profile' %}" class="nav-link border border-light rounded waves-effect text-white">حساب کاربری</a>
                </li>
              {% elif request.user.expert %}
                <li class="nav-item">
                  <a href="{% url 'dashboard' %}" class="nav-link border border-light rounded waves-effect text-white">حساب کاربری</a>
                </li>
              {% else %}
              {% endif %}
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link border border-light rounded waves-effect text-white">خروج</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a href="{% url 'signup_customer' %}" class="nav-link border border-light rounded waves-effect text-white">ثبت نام</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'login' %}" class="nav-link border border-light rounded waves-effect text-white">ورود</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
  </header>

media/templates/home/home.html
{% extends 'home/main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body %}
<main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <h1>خدمات</h1>
        <form class="form-inline mx-auto w-50" method="GET">
            {{myfilter.form.hashtag|add_class:"form-control mr-3 w-75"}}
          <button class="btn btn-info" type="submit">Search</button>
        </form>
        {% if messages %}
          {% for message in messages %}
          <p class="lead text-muted text-info">{{message}}</p>
          {% endfor %}
        {% endif %}
      </div>
    </section>
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          {% for category in categorys %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{category.image.url}}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"></img>
                <div class="card-body">
                    <h6 class="card-title">{{category.title}}</h6>
                    <p class="card-text">{{category.description}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-info " href="{% url 'category' category.id %}">View</a>
                    </div>
                    <small class="text-muted">{{category.expert_set.all.count}} متخصص</small>
                    </div>
                </div>
                </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </main>
{% endblock body %}

media/templates/home/main.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Home</title>
  </head>
  <body class="bg-light" dir="rtl">
    {% include "home/header.html" %}
    {% block body %}
      
    {% endblock body %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>