srv/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls , name='Programer'),
    path('', include('shop.urls')),
]

shop/models.py
from django.contrib.auth.models import Group, User
from django.db import models


# Create your models here

class Expert(models.Model):
    user        = models.OneToOneField(to=User,on_delete=models.CASCADE)
    username    = models.CharField(max_length=35)
    first_name  = models.CharField(max_length=35)
    last_name   = models.CharField(max_length=35)
    image       = models.ImageField(upload_to='image expert/', default='image/avatar.png', blank=True, null=True)
    address     = models.CharField(max_length=250)
    phone       = models.CharField(max_length=12)
    email       = models.EmailField(max_length=254)
    category    = models.ManyToManyField(to='Category')
    def __str__(self):
        return self.username

class Customer(models.Model):
    user        = models.OneToOneField(to=User , on_delete=models.CASCADE)
    username    = models.CharField(max_length=35)
    first_name  = models.CharField(max_length=35)
    last_name   = models.CharField(max_length=35)
    phone       = models.CharField(max_length=12)
    email       = models.EmailField(max_length=254)
    def __str__(self):
        return self.username
    
class Tag(models.Model):
    title = models.CharField(max_length=35)
    def __str__(self):
        return self.title
    
class Category(models.Model):
    title   = models.CharField(max_length=35)
    image   = models.ImageField(upload_to='image category/', default='image/default.jpg', blank=True, null=True)
    description = models.CharField(max_length=255 , blank=True , null=True)
    hashtag = models.CharField(max_length=200 , null=True)
    tag     = models.ForeignKey(to=Tag,on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
class Request_srv(models.Model):
    title       = models.CharField(max_length=35)
    phone       = models.CharField(max_length=12)
    address     = models.CharField(max_length=100)
    category    = models.ForeignKey(to=Category,on_delete=models.CASCADE)
    description = models.CharField(max_length=300,blank=True,null=True)
    expert      = models.ForeignKey(to=Expert,on_delete=models.CASCADE)
    customer    = models.ForeignKey(to=Customer,on_delete=models.CASCADE)
    update_time = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

media/templates/dashboard/dashboard.html
{% extends 'dashboard/main.html' %}
{% block body %}
    {% include "dashboard/searchbox.html" %}      
    <div class="row wow fadeIn">
      {% if messages %}
        <div class="container">
          <div class="card mb-4 wow fadeIn">
              <div class="card-body mx-auto">
                {% for message in messages %}
                  <h6 class="card-title btn btn-info ">{{message}}</h6>
                {% endfor %}
              </div>
          </div>
        </div> 
      {% endif %}
      {% if Requests %}
          {% for Request in Requests %}
          <div class="col-md-6 mb-4">
              <div class="card">
                  <div class="card-header">{{Request.title}}</div>
                  <div class="card-body">
                      <h5 class="card-title">{{Request.category.title}}</h5>
                      <p class="card-text">{{Request.description}}</p>
                  </div>
              </div>
          </div>
          {% endfor %}
      {% else %}
          <div class="col">
              <div class="card">
                  <div class="card-body mx-auto">
                      <h2 class="card-title btn btn-info">شما هیچ درخواستی ندارید.</h2>
                  </div>
              </div>
          </div> 
          {% endif %}
    </div>
{% endblock body %}

media/templates/dashboard/form.html
{% extends 'dashboard/main.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body %}
<div class="row wow fadeIn">
    <div class="container w-50">
        <div class="card">
          <div class="card-body">
            <form method="POST" dir="rtl" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_first_name" class="float-right">نام:</label>
                    {{form.first_name|add_class:"form-control"}}
                </div>
                {% if form.first_name.errors %}
                <div class="btn btn-sm-6 btn-warning">
                    {{ form.first_name.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_last_name" class="float-right">نام خانوادگی:</label>
                    {{form.last_name|add_class:"form-control"}}
                </div>
                {% if form.last_name.errors %}
                <div class="btn btn-sm-6 btn-warning">
                    {{ form.last_name.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_image" class="float-right">عکس:</label>
                    {{form.image|add_class:"form-control-file"}}
                </div>
                {% if form.image.errors %}
                <div class="btn btn-sm-6 btn-warning">
                    {{ form.image.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_phone" class="float-right">تلفن:</label>
                    {{form.phone|add_class:"form-control"}}
                </div>
                {% if form.phone.errors %}
                <div class="btn btn-sm-6 btn-warning">
                    {{ form.phone.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_email" class="float-right">ایمیل:</label>
                    {{form.email|add_class:"form-control"}}
                </div>
                {% if form.email.errors %}
                <div class="btn btn-sm-6 btn-warning">
                    {{ form.email.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_category" class="float-right">دسته بندی:</label>
                    {{form.category|add_class:"form-control"}}
                </div>
                {% if form.category.errors %}
                <div class="btn btn-sm-6 btn-warning">
                    {{ form.category.errors }}
                </div>
                {% endif %}
                <div class="form-group">
                    <label for="id_address" class="float-right">ادرس:</label>
                    {{form.address|add_class:"form-control"}}
                </div>
                {% if form.address.errors %}
                <div class="btn btn-sm-6 btn-warning">
                    {{ form.address.errors }}
                </div>
                {% endif %}
                <input type="submit" class="btn btn-primary" value="ذخیره" >
              </form>
          </div>
        </div>
    </div>
</div>
{% endblock body %}

media/templates/dashboard/header.html
{% load static %}
  <!--Main Navigation-->
  <header>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
      <div class="container-fluid">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'home' %}" >
          <strong class="blue-text">Coding</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link waves-effect" href="{% url 'dashboard' %}">صفحه اصلی
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="#">پیام ها</a>
            </li>
          </ul>
          <!-- Right -->
          <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
              <a href="{% url 'settings' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fa fa-gear mr-2"></i>تنظیمات
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'logout' %}" class="nav-link border border-light rounded waves-effect">خروج</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->
  </header>

media/templates/dashboard/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Dashboard</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
</head>
<body class="grey lighten-3" dir="rtl">
    {% include "dashboard/header.html" %}
  <!--Main layout-->
  <main class="container pt-5 mx-auto">
    <div class="container mt-5 mx-auto">
    
    {% block body %}
      
    {% endblock body %}
    </div>
  </main>
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>  
</html>
  

media/templates/dashboard/request_list.html
{% extends 'dashboard/main.html' %}
{% load static %}
{% block body %}
<div class="row wow fadeIn">
    {% if request.user.expert.request_srv_set.all %}
        {% for Request in request.user.expert.request_srv_set.all %}
        <div class="col-md-6 mb-4">
            <div class="card">
                <div class="card-header">{{Request.title}}</div>
                <div class="card-body">
                    <h5 class="card-title">{{Request.category.title}}</h5>
                    <p class="card-text">{{Request.description}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">شما هیچ درخواستی ندارید</h6>
            </div>
        </div>
    </div> 
    {% endif %}
</div>
{% endblock body %}

media/templates/dashboard/searchbox.html
{% load widget_tweaks %}
<!-- Heading -->
      <div class="card mb-4 wow fadeIn">

        <!--Card content-->
        <div class="card-body d-sm-flex justify-content-between">

          <h4 class="mb-2 mb-sm-0 pt-1">
            <a href="#">صفحه اصلی</a>
            <span>/</span>
            <span>درخواست ها</span>
          </h4>
          <form class="d-flex justify-content-center" method="GET" >
            <!-- Default input -->
            {{myfilter.form.title|add_class:"form-control"}}
            <button class="btn btn-primary btn-sm my-0 p" type="submit">
              <i class="fas fa-search"></i>
            </button>

          </form>
        </div>
      </div>
      <!-- Heading -->